# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_learn_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习时长'),
        ),
    ]
