# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_say',
            field=models.CharField(default='', max_length=300, verbose_name='老师说'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_needknow',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
